Repository openshift/openshift-restclient-java, pull requests merged in 2019-05, with the labels that each got.

#362 [360] impl'd IPod#isReady that relies on all containers to be ready
  src/main/java/com/openshift/internal/restclient/model/Pod.java
  src/main/java/com/openshift/restclient/model/IPod.java
  src/test/java/com/openshift/internal/restclient/model/v1/PodTest.java
  src/test/java/com/openshift/restclient/utils/Samples.java
  src/test/resources/samples/openshift3/v1_pod_multiContainer_ready.json
Labels: ok-to-test, size/XL

#381 Use JDK11 instead of JDK9 in travis
  .travis.yml
Labels: lgtm, ok-to-test, size/XS

#383 OSJC-285: fix CVE-2018-20200
  pom.xml
Labels: lgtm, ok-to-test, size/XS

#380 OSJC-284: Authorize URL is computed from baseURL use /.well-known/oau…
  src/main/java/com/openshift/internal/restclient/DefaultClient.java
  src/main/java/com/openshift/internal/restclient/authorization/AuthorizationContext.java
  src/main/java/com/openshift/internal/restclient/okhttp/OpenShiftAuthenticator.java
  src/main/java/com/openshift/restclient/IClient.java
Labels: lgtm, size/M

#384 releasing 7.1.1.Final
  pom.xml
Labels: lgtm, size/XS

#385 Bumping to 8.0.0-SNAPSHOT as we are going to support OpenShift 4
  pom.xml
Labels: lgtm, size/XS
