Repository openshift/openshift-restclient-java, pull requests merged in 2019-11, with the labels that each got.

#414 /healthz should not trigger auth
  src/main/java/com/openshift/internal/restclient/DefaultClient.java
  src/main/java/com/openshift/internal/restclient/okhttp/AuthenticatorInterceptor.java
Labels: lgtm, ok-to-test, size/XS

#411 authorize by direct request to auth-endpoint (was: using invalid bearer & authenticator indirection)
  src/main/java/com/openshift/internal/restclient/okhttp/AuthenticatorInterceptor.java
  src/main/java/com/openshift/internal/restclient/okhttp/OpenShiftRequestBuilder.java
Labels: lgtm, ok-to-test, size/M

#409 Update IClient.java
  src/main/java/com/openshift/restclient/IClient.java
Labels: lgtm, size/XS
