Repository openshift/openshift-restclient-java, pull requests merged in 2020-01, with the labels that each got.

#419 upgrade log4j, sl4j to latest versions (#418)
  pom.xml
Labels: lgtm, ok-to-test, size/S

#425 fix NPE when using unreachable server (#424)
  src/main/java/com/openshift/internal/restclient/AuthorizationEndpoints.java
  src/main/java/com/openshift/internal/restclient/DefaultClient.java
  src/main/java/com/openshift/internal/restclient/RequestingSupplier.java
  src/main/java/com/openshift/internal/restclient/okhttp/AuthenticatorInterceptor.java
  src/main/java/com/openshift/restclient/IClient.java
  src/test/java/com/openshift/internal/restclient/ClusterVersionsTest.java
Labels: lgtm, ok-to-test, size/L

#427 removed unnecessary param request when testing if url needs auth
  src/main/java/com/openshift/internal/restclient/okhttp/AuthenticatorInterceptor.java
Labels: lgtm, size/S

#422 Fix OCP startup script
  .travis.yml
  startOCP.sh
Labels: lgtm, size/S

#429 dont re-authorize an authorization request (#423)
  src/main/java/com/openshift/internal/restclient/okhttp/AuthenticatorInterceptor.java
Labels: lgtm, size/S

#431 correctly handle challenge headers with 'realm=' (#430)
  src/main/java/com/openshift/internal/restclient/okhttp/BasicChallengeHandler.java
  src/main/java/com/openshift/restclient/http/IHttpConstants.java
  src/test/java/com/openshift/internal/restclient/okhttp/BasicChallangeHandlerTest.java
Labels: lgtm, size/XS
