Repository openshift/openshift-restclient-java, pull requests merged in 2020-02, with the labels that each got.

#433 Issue-418 Update log4j configuration for 2.13.0
  src/test/resources/log4j.xml
Labels: lgtm, size/M

#434 Bump sl4j api version
  pom.xml
Labels: lgtm, size/S

#438 corrected IRSyncable#Peer#toString (#437)
  src/main/java/com/openshift/restclient/capability/resources/IRSyncable.java
Labels: lgtm, size/XS

#436 only log to slf4j (use log4j2 only in tests, integration-tests)
  pom.xml
  src/main/java/com/openshift/internal/restclient/RequestingSupplier.java
  src/main/java/com/openshift/internal/restclient/api/capabilities/PodExec.java
  src/main/java/com/openshift/internal/restclient/capability/resources/DeployCapability.java
  src/main/java/com/openshift/internal/restclient/okhttp/ResponseCodeInterceptor.java
  src/main/java/com/openshift/internal/util/URIUtils.java
  src/test/resources/log4j.xml
  src/test/resources/log4j2.xml
Labels: lgtm, ok-to-test, size/L

#435 bumped to 8.1.1.Final
  pom.xml
Labels: lgtm, size/XS
